from fastmcp.tool_decorator import mcp_tool
from fastmcp.data_models import ToolContext, TextContent
from typing import List, Dict, Any, Optional
import json

from agentic_framework_pkg.mcp_server.vector_store_manager import VectorStoreManager
from agentic_framework_pkg.logger_config import get_logger # Assuming shared logger
# from ..embedding_utils import get_embeddings # Placeholder for your embedding logic

logger = get_logger(__name__)

@mcp_tool(
    name="add_to_vector_store",
    description="Adds documents and their embeddings to a specified vector store collection.",
    input_schema={
        "type": "object",
        "properties": {
            "collection_name": {"type": "string", "description": "Name of the collection."},
            "documents": {"type": "array", "items": {"type": "string"}, "description": "List of document texts."},
            "embeddings": {"type": "array", "items": {"type": "array", "items": {"type": "number"}}, "description": "Optional list of embeddings. If not provided, they might be generated by the store if configured."},
            "metadatas": {"type": "array", "items": {"type": "object"}, "description": "Optional list of metadata dictionaries."},
            "ids": {"type": "array", "items": {"type": "string"}, "description": "Optional list of document IDs."},
            "mcp_session_id": {"type": "string", "description": "MCP session ID for context."},
        },
        "required": ["collection_name", "documents", "mcp_session_id"],
    }
)
async def add_to_vector_store_tool(params: Dict[str, Any], context: ToolContext) -> List[TextContent]:
    try:
        vsm = VectorStoreManager()
        vsm.add_documents(
            collection_name=params["collection_name"],
            documents=params["documents"],
            embeddings=params.get("embeddings"),
            metadatas=params.get("metadatas"),
            ids=params.get("ids")
        )
        return [TextContent(text=json.dumps({"status": "success", "message": f"Added {len(params['documents'])} documents to '{params['collection_name']}'."}))]
    except Exception as e:
        logger.error(f"Error in add_to_vector_store_tool: {e}", exc_info=True)
        return [TextContent(text=json.dumps({"status": "error", "message": str(e)}))]

@mcp_tool(
    name="query_vector_store",
    description="Queries a specified vector store collection.",
    input_schema={
        "type": "object",
        "properties": {
            "collection_name": {"type": "string", "description": "Name of the collection to query."},
            "query_texts": {"type": "array", "items": {"type": "string"}, "description": "List of query texts. Embeddings will be generated."},
            "query_embeddings": {"type": "array", "items": {"type": "array", "items": {"type": "number"}}, "description": "Alternatively, provide pre-computed query embeddings."},
            "n_results": {"type": "integer", "default": 5, "description": "Number of results to return."},
            "where_filter": {"type": "object", "description": "Optional filter for metadata."},
            "mcp_session_id": {"type": "string", "description": "MCP session ID for context."},
        },
        "required": ["collection_name", "mcp_session_id"], # Either query_texts or query_embeddings also effectively required
    }
)
async def query_vector_store_tool(params: Dict[str, Any], context: ToolContext) -> List[TextContent]:
    try:
        vsm = VectorStoreManager()
        # Here you would generate embeddings for query_texts if not provided as query_embeddings
        # For simplicity, assuming query_embeddings are provided or your VSM handles text embedding
        if params.get("query_texts") and not params.get("query_embeddings"):
            # embeddings = get_embeddings(params["query_texts"]) # Placeholder
            # params["query_embeddings"] = embeddings
            pass # Implement embedding generation for query_texts if needed

        results = vsm.query_collection(
            collection_name=params["collection_name"],
            query_embeddings=params.get("query_embeddings"), # Prioritize provided embeddings
            query_texts=params.get("query_texts"), # Fallback to texts if VSM handles embedding
            n_results=params.get("n_results", 5),
            where=params.get("where_filter")
        )
        return [TextContent(text=json.dumps({"status": "success", "results": results}))]
    except Exception as e:
        logger.error(f"Error in query_vector_store_tool: {e}", exc_info=True)
        return [TextContent(text=json.dumps({"status": "error", "message": str(e)}))]